repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.2
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: ^src/crewai/cli/templates/
      - id: ruff-format
        exclude: ^src/crewai/cli/templates/
